USE Test;

 /* 11.11.2019 */
CREATE TABLE [Test].[dbo].[Albums](
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ItemId INT FOREIGN KEY REFERENCES Sights(Id) ON DELETE CASCADE NOT NULL,
	ImageName VARCHAR(50),
	Title VARCHAR(50),
	IsMain BIT NOT NULL DEFAULT 0
);

ALTER TABLE [Test].dbo.[Albums] ALTER COLUMN Title VARCHAR(50) NOT NULL;