/* 10.22.2019 */
USE Test;

CREATE TABLE Reviews (
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	ParentId INT,
	ItemId INT FOREIGN KEY REFERENCES Sights(Id),
	[Message] TEXT NOT NULL,
	AuthorId INT NOT NULL
);

ALTER TABLE Reviews ADD PRIMARY KEY (Id);

ALTER TABLE Reviews ADD CONSTRAINT FK_ParentReview FOREIGN KEY (ParentId) REFERENCES Reviews(Id);

ALTER TABLE Reviews DROP CONSTRAINT FK_ParentReview;

DROP TABLE Reviews;